sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - curl -i http://circleofmusic-sidzi.rhcloud.com
    - curl -o $TRAVIS_BUILD_DIR/app/myreleasekey.jks http://circleofmusic-sidzi.rhcloud.com/getSigningKey

script: ./gradlew clean assembleRelease

after_success:
    - VERSIONINFOAPP="$(cat $TRAVIS_BUILD_DIR/app/build.gradle | grep "versionCode" | tr ' ' '\n' | grep -e "\d")"
    - curl -i http://circleofmusic-sidzi.rhcloud.com/updateAppVersion$VERSIONINFOAPP
    - curl -i -F file=@$TRAVIS_BUILD_DIR/app/build/outputs/apk/app-release.apk http://circleofmusic-sidzi.rhcloud.com/uploadApk
