sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean build

after_success:
    - cp app/build/outputs/apk/app-debug.apk .
    - curl -i -F filedata=@/tmp/hello.txt https://transfer.sh
