sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
