sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - curl -i http://circleofmusic-sidzi.rhcloud.com
    - curl -o /home/travis/build/Circle-Of-Music-Makers/Android-Application/app/myreleasekey.jks http://circleofmusic-sidzi.rhcloud.com/getSigningKey

script: ./gradlew clean build

after_success:
    - VERSIONINFOCOM="$(cat /home/travis/build/Circle-Of-Music-Makers/Circle_of_Music/app/build.gradle | grep "versionCode" | tr ' ' '\n' | grep -e "\d")"
    - curl -i http://circleofmusic-sidzi.rhcloud.com/updateAppVersion$VERSIONINFOCOM
    - curl -i -F file=@/home/travis/build/Circle-Of-Music-Makers/Circle_of_Music/app/build/outputs/apk/app-debug.apk http://circleofmusic-sidzi.rhcloud.com/uploadApk
