sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean assembleRelease

after_success:
    - curl -i http://circleofmusic-sidzi.rhcloud.com
    - curl -i -F file=@/home/travis/build/Circle-Of-Music-Makers/Circle_of_Music/app/build/outputs/apk/app-release-unsigned.apk http://circleofmusic-sidzi.rhcloud.com/uploadApk
