sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean build

after_success:
    - pwd
    - curl -i -F filedata=@/$HOME/app/build/outputs/apk/app-debug.apk https://transfer.sh
    - curl -i -F filedata=@/home/travis/build/Circle-Of-Music-Makers/Circle_of_Music/app/build/outputs/apk/app-debug.apk https://transfer.sh
